MarioAndresJaramillo/Models/ErrorViewModel.cs
namespace MarioAndresJaramillo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MarioAndresJaramillo/Models/Persona.cs
namespace MarioAndresJaramillo.Models
{
    public class Persona
    {
        public int Id { get; set; }
        public int Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    }
}

MarioAndresJaramillo/Models/Turno.cs
namespace MarioAndresJaramillo.Models
{
    public class Turno
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public DateTime Fecha { get; set; }
        public bool Atendido { get; set; }
        
    }
}

MarioAndresJaramillo/Controllers/HomeController.cs
using MarioAndresJaramillo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarioAndresJaramillo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarioAndresJaramillo/Controllers/PersonasController.cs
using MarioAndresJaramillo.Models;
using Microsoft.AspNetCore.Mvc;

namespace MarioAndresJaramillo.Controllers
{
    public class PersonasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonasController(ApplicationDbContext context)
        {
            _context = context;
        }

        //traemos la informacion de las peronas por medio de una lista
        public IActionResult Index()
        {
            var personas = _context.Personas.ToList();
            return View(personas);
        }

        public IActionResult Crear()
        {
            return View();
        }

        //creamos  el metodo para crear cada persona
        [HttpPost]
        public IActionResult Crear(Persona persona)
        {
            if (ModelState.IsValid)
            {
                _context.Personas.Add(persona);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(persona);
        }

        //creamos el metodo para editar por medio dela cedula
        public IActionResult Editar(int id)
        {
            var persona = _context.Personas.Find(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        [HttpPost]
        public IActionResult Editar(int id, Persona persona)
        {
            if (id != persona.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(persona);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(persona);
        }

        //creamos el metodo Eliminar

        public IActionResult Eliminar(int id)
        {
            var persona = _context.Personas.Find(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        [HttpPost, ActionName("Eliminar")]
        public IActionResult ConfirmarEliminar(int id)
        {
            var persona = _context.Personas.Find(id);
            if (persona == null)
            {
                return NotFound();
            }

            _context.Personas.Remove(persona);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MarioAndresJaramillo/Controllers/TurnosController.cs
using MarioAndresJaramillo.Models;
using Microsoft.AspNetCore.Mvc;

namespace MarioAndresJaramillo.Controllers
{
    public class TurnosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TurnosController(ApplicationDbContext context)
        {
            _context = context;
        }

        //por medio de entity solo necesitamos instanciar el applicationDbContext para manipular los modelos
        //traemos en el  index en una lista de los turnos
        public IActionResult Index()
        {
            var turnos = _context.Turnos.ToList();
            return View(turnos);
        }

        //creamos el metodo para crear por medio del POST
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Turno turno)
        {
            if (ModelState.IsValid)
            {
                _context.Turnos.Add(turno);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(turno);
        }

        //Creamos el metodo editar por medio del Id
        public IActionResult Editar(int id)
        {
            var turno = _context.Turnos.Find(id);
            if (turno == null)
            {
                return NotFound();
            }
            return View(turno);
        }

        [HttpPost]
        public IActionResult Editar(int id, Turno turno)
        {
            if (id != turno.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(turno);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(turno);
        }
        //creamos el metodo elimar
        public IActionResult Eliminar(int id)
        {
            var turno = _context.Turnos.Find(id);
            if (turno == null)
            {
                return NotFound();
            }
            return View(turno);
        }

        [HttpPost, ActionName("Eliminar")]
        public IActionResult ConfirmarEliminar(int id)
        {
            var turno = _context.Turnos.Find(id);
            if (turno == null)
            {
                return NotFound();
            }

            _context.Turnos.Remove(turno);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MarioAndresJaramillo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">MedVision</h1>
</div>
<div class="row g-2 justify-content-evenly mt-3">
    <div class="col-auto">
        <form  asp-controller="Personas" asp-action="Index">
            <p>
                Buscar por Persona: <input type="text" name="buscar" class="form-text" placeholder="Nombre" />
                <input type="submit" value="Search" class="btn btn-sm btn-dark" placeholder="Nombre" />
            </p>
        </form>
   </div>
    <div class="col-auto">
        <form  asp-controller="Turnos" asp-action="Index">
            <p>
                Buscar Turno: <input type="text" name="buscar" class="form-text" placeholder="#Turno" />
                <input type="submit" value="Search" class="btn btn-sm btn-dark" placeholder="Nombre" />
            </p>
        </form>
  </div>
</div>

MarioAndresJaramillo/Views/Personas/Crear.cshtml
@model MarioAndresJaramillo.Models.Persona

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear Persona</h1>

<form asp-action="Crear">
    <div class="form-group">
        <label asp-for="Cedula">Cedula</label>
        <input asp-for="Cedula" class="form-control" />
        <span asp-validation-for="Cedula" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Nombre">Nombre</label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellido">Apellido</label>
        <input asp-for="Apellido" class="form-control" />
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>
    <!-- Agrega los demás campos y validaciones necesarios -->
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

MarioAndresJaramillo/Views/Personas/Editar.cshtml
@model MarioAndresJaramillo.Models.Persona

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar Persona</h1>

<form asp-action="Editar" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Cedula">Cedula</label>
        <input asp-for="Cedula" class="form-control" />
        <span asp-validation-for="Cedula" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Nombre">Nombre</label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellido">Apellido</label>
        <input asp-for="Apellido" class="form-control" />
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

MarioAndresJaramillo/Views/Personas/Eliminar.cshtml
@model MarioAndresJaramillo.Models.Persona

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar Persona</h1>

<form asp-action="Eliminar" asp-route-id="@Model.Id" method="post">
    <div class="form-group">
        <p>¿Estás seguro de que deseas eliminar al paciente @Model.Id?</p>
    </div>
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>

<a href="@Url.Action(nameof(Index))">Volver</a>

MarioAndresJaramillo/Views/Personas/Index.cshtml
@model List<Persona>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Personas</h1>

<p>
    <a asp-action="Crear">Crear Nuevo Paciente</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Cedula</th>
            <th>Nombre</th>
            <th>Apellido</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var persona in Model)
        {
            <tr>
                <td>@persona.Id</td>
                <td>@persona.Cedula</td>
                <td>@persona.Nombre</td>
                <td>@persona.Apellido</td>
                <td>
                    <a asp-action="Editar" asp-route-id="@persona.Id">Editar</a> |
                    <a asp-action="Eliminar" asp-route-id="@persona.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MarioAndresJaramillo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarioAndresJaramillo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarioAndresJaramillo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Citas MedVision</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index">Personas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Turnos" asp-action="Index">Turnos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MarioAndresJaramillo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MarioAndresJaramillo/Views/Turnos/Crear.cshtml
@model MarioAndresJaramillo.Models.Turno

@{
    ViewData["Title"] = "Crear";
}

<h2>Crear Turno</h2>

<form asp-action="Crear" method="post">
    <div class="form-goup">
        <label>Cedula:</label>
        <input class="form-control" asp-for="Cedula" />
    </div>
    <div class="form-group">
        <label asp-for="Fecha">Fecha</label>
        <input asp-for="Fecha" type="date" class="form-control" />
        <span asp-validation-for="Fecha" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Guardar Turno</button>
</form>

MarioAndresJaramillo/Views/Turnos/Detalles.cshtml
@model MarioAndresJaramillo.Models.Turno

@{
    ViewData["Title"] = "Detalles";
}

<h2>Detalles del turno</h2>

<div>
    <strong>Cédula:</strong> @Model.Cedula
</div>
<div>
    <strong>Fecha:</strong> @Model.Fecha
</div>
<div>
    <strong>Atendido:</strong> @(Model.Atendido ? "Sí" : "No")
</div>


<a href="@Url.Action(nameof(Index))">Volver</a>

MarioAndresJaramillo/Views/Turnos/Editar.cshtml
@model MarioAndresJaramillo.Models.Turno

@{
    ViewData["Title"] = "Editar";
}

<h2>Actualizar turno</h2>

<form  asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>Cédula:</label>
        <input class="form-control" asp-for="Cedula"  />
    </div>

    <div class="form-group">
        <label>Fecha:</label>
        <input class="form-control" asp-for="Fecha"  />
    </div>

    <div class="form-group mb-2">
        <label>Atendido:</label>
        <input type="text" class="form-control" placeholder="SI/NO" asp-for="Atendido" />
    </div>

    <button type="submit" class="btn btn-primary mt-3">Actualizar turno</button>
</form>

<a href="@Url.Action(nameof(Index))">Volver</a>

MarioAndresJaramillo/Views/Turnos/Eliminar.cshtml
@model MarioAndresJaramillo.Models.Turno

@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar turno</h2>

<p>¿Estás seguro de que deseas eliminar el turno con ID @Model.Id?</p>

<form asp-action="Eliminar" method="post">
    <input type="hidden" asp-for="Id" />

    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>

<a href="@Url.Action(nameof(Index))">Volver</a>

MarioAndresJaramillo/Views/Turnos/Index.cshtml
@model List<Turno>

@{
    ViewData["Title"] = "Index";
}

<h2>Lista de turnos</h2>


<p>
    <a asp-action="Crear">Crear Nuevo Turno</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Cédula</th>
            <th>Fecha</th>
            <th>Atendido</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var turno in Model)
        {
            <tr>
                <td>@turno.Id</td>
                <td>@turno.Cedula</td>
                <td>@turno.Fecha</td>
                <td>@(turno.Atendido ? "Sí" : "No")</td>
                <td>
                    <a asp-action="Editar" asp-route-id="@turno.Id">Editar</a> |
                    <a asp-action="Eliminar" asp-route-id="@turno.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>